# Generated by Django 6.0.2 on 2026-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ministerio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('leader', models.CharField(max_length=100, verbose_name='Líder')),
                ('meeting_time', models.CharField(blank=True, max_length=100)),
                ('meeting_location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ministries/')),
                ('icon_class', models.CharField(default='fa-heart', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
                'ordering': ['order', 'name'],
            },
        ),
    ]
