# Generated by Django 6.0.2 on 2026-04-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Imagen de fondo del Hero')),
                ('titulo', models.CharField(default='Comunidad Cristiana de la Villa', max_length=200, verbose_name='Título principal')),
                ('subtitulo', models.CharField(default='Viviendo en el poder del evangelio', max_length=200, verbose_name='Subtítulo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Hero',
                'verbose_name_plural': 'Configuración del Hero',
            },
        ),
    ]
