# Generated by Django 6.0.2 on 2026-03-02 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('speaker', models.CharField(max_length=100, verbose_name='Predicador')),
                ('date_preached', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('bible_text', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sermons/images/')),
            ],
            options={
                'verbose_name': 'Sermón',
                'verbose_name_plural': 'Sermones',
                'ordering': ['-date_preached'],
            },
        ),
    ]
